web:
    image: nginx:latest
    ports:
        - "8081:80"
    volumes:
        - ./code:/usr/share/nginx/html/code/
        - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
        - php
php:
    image: php:7-fpm
    volumes:
        - ./code:/usr/share/nginx/html/code/
